config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
      post 'notify'
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'
  get '/recipes/:id/notify', to: 'recipes#notify'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # Association
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  # mount_uploader :picture, PictureUploader
  require 'carrierwave/orm/activerecord'
  # validate :picture_size

  def thumbs_up_total
    # self reprezentuje obiekt na rzecz którego wywołano metodę
    likes.where(like: true).size
  end

  def thumbs_down_total
    likes.where(like: false).size
  end

  private

  def picture_size
    if picture_size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end

  has_attached_file :picture, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like, :notify]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_user_like, only: [:like]
  before_action :admin_user, only: [:destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    if @recipe.save
      flash[:success] = "You're recipe was created succesfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'Your recipe was updated succesfully'
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = 'Your selection was successful'
      redirect_to :back
    else
      flash[:danger] = 'You can only like/dislike a recipe once'
      redirect_to :back
    end
  end

  def notify
    mail = UserMailer.recipe_notify(@recipe).deliver
    if !!mail
      flash[:success] = 'Recipe has been sent.'
      redirect_to :back
    else
      flash[:danger] = "You can't sent recipe"
      redirect_to :back
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe Deleted"
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
  end

  def require_same_user
    if current_user != @recipe.chef and !current_user.admin?
      flash[:danger] = 'You can only edit your own recipes'
      redirect_to recipes_path
    end
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_user_like
    unless logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to :back
    end
  end

  def admin_user
      redirect_to recipes_path unless current_user.admin?
  end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { mulitpart: true }) do |r| %>
    <%= r.label :name %>
    <%= r.text_field :name %>

    <%= r.label :summary %>
    <%= r.text_field :summary %>

    <%= r.label :description %>
    <%= r.text_area :description, rows: 10 %>
    <strong>Styles:
    </strong>
    <%= r.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    <br><br>
    <strong>Ingredients:
    </strong>
    <%= r.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
    <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
    <% end %>
    <br><br>

    <span class="picture">
      <%= r.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <%= r.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function () {
    size_in_megabytes = this.files[0].size / 1024 / 1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>
<%= will_paginate @recipe %>
<% @recipes.each do |recipe| %>
<div class="row">
  <div class="col-md-2">
    <section class="chef_info center">
      <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
      <h5>Chef name:
        <%= recipe.chef.chefname %></h5>
    </section>
  </div>

  <div class="col-lg-6 well">
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>
    <% if recipe.styles.any? %>
    <p>Styles:
      <%= render recipe.styles %></p>
    <% end %>
    <% if recipe.ingredients.any? %>
    <p>Ingredients:
      <%= render recipe.ingredients %></p>
    <p>
      <% end %>
      <span class='quiet'>
        <small>created:
          <%= time_ago_in_words(recipe.created_at) %>
          ago,
        </small>
      </span>
      <span class='quiet'>
        <small>updated:
          <%= time_ago_in_words(recipe.updated_at) %>
          ago</small>
      </span>
    </p>
    <div class="pull-right">
      <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp
      <%= recipe.thumbs_up_total %>
      <% end %>&nbsp&nbsp&nbsp&nbsp
      <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp
      <%= recipe.thumbs_down_total %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
  </div>
</div>
<hr/>
<% end %>
<%= will_paginate @recipe %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    <p>
      <h5>Brought to you by:
        <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
    <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <%= link_to "Email this Recipe", notify_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>
    <% if logged_in? and current_user.admin? %>
    <%= link_to "[Delete Recipe]", @recipe, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    <div class="well">
      <% if @recipe.styles.any? %>
      <p>Styles:
        <%= render @recipe.styles %></p>
      <% end %>
      <% if @recipe.ingredients.any? %>
      <p>Ingredients:
        <%= render @recipe.ingredients %></p>
      <% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp
        <%= @recipe.thumbs_up_total %>
        <% end %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp
        <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %></h5>